=== vitrums/apprunner/AppRunner/config/apprunner-module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="non_empty_string_type">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="boolean_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="true" />
      <xs:enumeration value="false" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="scope_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="compile" />
      <xs:enumeration value="provided" />
    </xs:restriction>
  </xs:simpleType>

  <!-- definition of attributes -->
  <xs:attribute name="name" type="non_empty_string_type" />
  <xs:attribute name="value" type="non_empty_string_type" />

  <xs:attribute name="starts-with" type="non_empty_string_type" />
  <xs:attribute name="ends-with" type="non_empty_string_type" />
  <xs:attribute name="contains" type="non_empty_string_type" />

  <xs:complexType name="constants_type">
    <xs:annotation>
      <xs:documentation source="description">
        Parent element for &lt;constant&gt; elements.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="constant" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation source="description">
            &lt;constant&gt; is a (name,value) pair. When
            referenced from within a document, ${CONSTANT_NAME} syntax should be used.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:attribute ref="name" />
          <xs:attribute name="value" type="xs:string" use="optional" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="namespace" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:complexType name="file_name_type">
    <xs:annotation>
      <xs:documentation source="description">
        Denotes a valid file name of a file residing in the
        directory specified by "in" attribute.
        Attributes "starts-with", "ends-with" and "contains"
        specify the file.
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="in" type="non_empty_string_type" />
    <xs:attribute ref="starts-with" use="optional" />
    <xs:attribute ref="ends-with" use="optional" />
    <xs:attribute ref="contains" use="optional" />
  </xs:complexType>

  <!-- operation_group types (more types might be added later) -->
  <xs:complexType name="rename_type">
    <xs:annotation>
      <xs:documentation source="description">
        Directive to rename the given files by applying one
        or more of the rename options.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="files" type="file_name_type" />
      <xs:element name="replace-all" minOccurs="0">
        <xs:annotation>
          <xs:documentation source="description">
            Rename option, which tells the apprunner to
            replace all occurrences of the string given in "substring" attribute with the string
            specified in "with" attribute.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:attribute name="substring" type="non_empty_string_type" />
          <xs:attribute name="with" type="non_empty_string_type" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="move_type">
    <xs:annotation>
      <xs:documentation source="description">
        Directive to move the given file(s) to the directory
        represented by the "to" attribute.
      </xs:documentation>
    </xs:annotation>
    <xs:group ref="file_names_group" maxOccurs="unbounded" />
    <xs:attribute name="to" type="non_empty_string_type" />
  </xs:complexType>
  
  <xs:group name="operation_group">
    <xs:annotation>
      <xs:documentation source="description">
        Elements comprising one operation.
      </xs:documentation>
    </xs:annotation>
    <xs:choice>
      <xs:element name="rename" type="rename_type" />
      <xs:element name="move" type="move_type" />
      <xs:element name="copy" type="move_type" />
      <xs:element name="delete">
        <xs:complexType>
          <xs:group ref="file_names_group" maxOccurs="unbounded" />
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:group>
  
  <xs:group name="file_names_group">
    <xs:annotation>
      <xs:documentation source="description">
        Either a single file name or a collection of file names.
      </xs:documentation>
    </xs:annotation>
    <xs:choice>
      <xs:element name="file" type="file_name_type" />
      <xs:element name="files" type="file_name_type" />
    </xs:choice>
  </xs:group>

  <xs:complexType name="operation_def_type">
    <xs:annotation>
      <xs:documentation source="description">
        A definition of an operation.
      </xs:documentation>
    </xs:annotation>
    <xs:group ref="operation_group" minOccurs="0" maxOccurs="unbounded" />
    <xs:attribute ref="name" />
  </xs:complexType>

  <xs:complexType name="configuration_type">
    <xs:annotation>
      <xs:documentation source="description">
        Contains definitions of constants and operations.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="constants" type="constants_type" minOccurs="0" />
      <xs:element name="actions" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="operation" type="operation_def_type" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="actions_type">
    <xs:annotation>
      <xs:documentation source="description">
        Contains a list of actions for one task.
      </xs:documentation>
    </xs:annotation>
    <xs:choice maxOccurs="unbounded">
      <xs:element name="application">
        <xs:annotation>
          <xs:documentation source="description">
            Represents a call of an external process.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="execute" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation source="description">
                  One call of the enclosing process with the
                  list of arguments.
                </xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:element name="cli-key">
                    <xs:annotation>
                      <xs:documentation source="description">
                        Any string, that will be passed as
                        is to this application as a CLI arg.
                      </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                      <xs:attribute name="value" type="non_empty_string_type" />
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="cli-value">
                    <xs:annotation>
                      <xs:documentation source="description">
                        Any string, that will be wrapped in
                        "" and then passed to this application as a CLI arg.
                      </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                      <xs:attribute name="value" type="non_empty_string_type" />
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="file" type="file_name_type" />
                </xs:choice>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="executable" type="non_empty_string_type" />
        </xs:complexType>
      </xs:element>
      <xs:element name="operation">
        <xs:annotation>
          <xs:documentation source="description">
            Operation consists of a set of actions like
            move, delete, rename a file, which will be performed in the same order they appear in a
            document.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:group ref="operation_group" minOccurs="0" maxOccurs="unbounded" />
          <xs:attribute name="ref" type="non_empty_string_type" use="optional" />
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="task_type">
    <xs:annotation>
      <xs:documentation source="description">
        A unit of work, which combines a set of external
        calls and operations on files.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="constants" type="constants_type" minOccurs="0" />
      <xs:element name="actions" type="actions_type" />
    </xs:sequence>
    <xs:attribute ref="name" />
  </xs:complexType>

  <!-- Root -->
  <xs:element name="apprunner-module">
    <xs:annotation>
      <xs:documentation source="description">
        Root element of the document.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:all>
        <xs:element name="inherits" minOccurs="0">
          <xs:annotation>
            <xs:documentation source="description">
              Contains a list of parent modules to inherit.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="module" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation source="description">
                    A valid name of a XML file with a parent module.
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute ref="name" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="configuration" type="configuration_type" minOccurs="0" />
        <xs:element name="tasks" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="task" type="task_type" minOccurs="0"
                maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vitrums/apprunner/AppRunner/config/examples/t7_sound_module.xml
<?xml version="1.0" encoding="UTF-8"?>
<apprunner-module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../apprunner-module.xsd">
  <inherits>
    <module name="examples\tekken7-module.xml" />
  </inherits>

  <!-- Just an example of inheritance mechanism. -->
  <tasks>
    <task name="SoundLiliAsMasterRaven">
      <constants>
        <constant name="subpath" value="TekkenGame\Content\Sound\Voice" />
        <constant name="to" value="${quickbms_t7_out_dir}\${subpath}\${character_to}" />
        <constant name="from" value="${quickbms_t7_out_dir}\${subpath}\${character_from}" />
      </constants>
      <actions>
        <application executable="uasset_renamer">
          <execute>
            <file in="${to}" starts-with="_s_mon_atck_m01" />
            <file in="${from}" starts-with="frv_atk_m01" />
          </execute>
          <execute>
            <file in="${to}" starts-with="_s_mon_atck_m02" />
            <file in="${from}" starts-with="frv_atk_m02" />
          </execute>
          <execute>
            <file in="${to}" starts-with="_s_mon_atck_s01" />
            <file in="${from}" starts-with="frv_atk_s01" />
          </execute>
          <execute>
            <file in="${to}" starts-with="_s_mon_atck_s02" />
            <file in="${from}" starts-with="frv_atk_s02" />
          </execute>
          <execute>
            <file in="${to}" starts-with="_s_mon_atck_s03" />
            <file in="${from}" starts-with="frv_atk_s03" />
          </execute>
          <execute>
            <file in="${to}" starts-with="_s_mon_atck_s04" />
            <file in="${from}" starts-with="frv_atk_s04" />
          </execute>
          <execute>
            <file in="${to}" starts-with="_s_mon_dmg_s01" />
            <file in="${from}" starts-with="frv_dmg_s01" />
          </execute>
          <execute>
            <file in="${to}" starts-with="_s_mon_dmg_s02" />
            <file in="${from}" starts-with="frv_dmg_s02" />
          </execute>
          <execute>
            <file in="${to}" starts-with="_s_mon_dmg_s03" />
            <file in="${from}" starts-with="frv_dmg_s03" />
          </execute>
          <execute>
            <file in="${to}" starts-with="_s_mon_dmg_s04" />
            <file in="${from}" starts-with="frv_dmg_s04" />
          </execute>
        </application>
      </actions>
    </task>
  </tasks>
</apprunner-module>

=== vitrums/apprunner/AppRunner/config/test/module1.xml
<?xml version="1.0" encoding="UTF-8"?>
<apprunner-module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="apprunner-module.xsd">
  <configuration>
    <constants>
      <constant name="testing_dir" value="dir_for_integration_testing" />
      <constant name="original_dir" value="${testing_dir}/original" />
      <constant name="destination_dir" value="${testing_dir}/destination" />
      <constant name="new_dir" value="${destination_dir}/new" />
      <!-- Executable paths -->
      <constant name="uasset_renamer" value="${testing_dir}/apps/UassetRenamer.exe" />
    </constants>
    <actions>
      <operation name="remove-new-suffix">
        <rename>
          <files in="." ends-with="-new.uasset" />
          <replace-all substring="-new.uasset" with=".uasset" />
        </rename>
      </operation>
    </actions>
  </configuration>


  <tasks>
    <task name="run_uasset_on_two_files">
      <constants>
        <constant name="dir_for_test" value="${original_dir}" />
        <constant name="to" value="${dir_for_test}/uassets" />
        <constant name="from" value="${dir_for_test}/uassets" />
      </constants>
      <actions>
        <application executable="${uasset_renamer}">
          <execute>
            <file in="${to}" contains="lil" />
            <file in="${from}" contains="frv" />
          </execute>
        </application>
        <operation ref="remove-new-suffix" />
        <operation>
          <move to="${destination_dir}">
            <files in="." ends-with=".uasset" />
          </move>
        </operation>
      </actions>
    </task>


    <task name="copy_123">
      <actions>
        <operation>
          <copy to="${new_dir}">
            <files in="${original_dir}/dir001" ends-with="123.txt" />
          </copy>
        </operation>
      </actions>
    </task>
    
    <task name="rename_123_in_new">
      <actions>
        <operation>
          <rename>
            <files in="${new_dir}" contains="123" />
            <replace-all substring="123" with="321" />
          </rename>
        </operation>
      </actions>
    </task>


    <task name="delete_321_in_new">
      <actions>
        <operation>
          <delete>
            <file in="${new_dir}" contains="321" />
            <files in="${new_dir}" contains="321" />
          </delete>
        </operation>
      </actions>
    </task>


    <task name="copy_dir001_to_x_and_y_then_abc_to_dir001_in_x_and_then_dir001_from_y_to_x">
      <actions>
        <operation>
          <copy to="${destination_dir}/x">
            <files in="${original_dir}" ends-with="dir001" />
          </copy>
          <copy to="${destination_dir}/y">
            <files in="${original_dir}" ends-with="dir001" />
          </copy>
          <copy to="${destination_dir}/x">
            <files in="${original_dir}" ends-with="abc.txt" />
          </copy>
          <copy to="${destination_dir}/x">
            <files in="${destination_dir}/y" ends-with="dir001" />
          </copy>
        </operation>
      </actions>
    </task>
    
  </tasks>
</apprunner-module>

=== vitrums/apprunner/AppRunner/config/test/module2.xml
<?xml version="1.0" encoding="UTF-8"?>
<apprunner-module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="apprunner-module.xsd">
  <inherits>
    <module name="test\module1.xml" />
  </inherits>
  
  <tasks>
    <task name="delete_123_in_new">
      <actions>
        <operation>
          <delete>
            <file in="${new_dir}" contains="123" />
            <files in="${new_dir}" contains="123" />
          </delete>
        </operation>
      </actions>
    </task>
  </tasks>
</apprunner-module>
